version: '2.4'

services:
  octoprint:
    container_name: octoprint
    image: octoprint/octoprint
    restart: unless-stopped
    volumes:
    - /etc/docker/volume/octoprint/data:/octoprint
    environment:
      - ENABLE_MJPG_STREAMER=true
    labels:
      - "traefik.http.routers.octoprint.rule=Host(`octoprint.f3r.eu`)"
      - "traefik.http.routers.octoprint.tls=true"
      - "traefik.http.routers.octoprint.tls.certresolver=default"
