PRESET_PATH="$(pwd)/system-preset/00-endermite.preset"
COMPOSE_PATH="$(pwd)/docker-compose"

cd $COMPOSE_PATH

echo "# DO NOT TOUCH, this file is automatically generated" > $PRESET_PATH;

for dir in *; do
	echo "enable docker-compose@$dir.service" >> $PRESET_PATH;
done
