version: '3'

services:
  traefik:
    container_name: traefik
    image: traefik:v2.9
    command: --api.insecure=true --providers.docker
    privileged: true
    network_mode: "host"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock