version: "3.9"

services:
  traefik:    
    container_name: traefik
    image: traefik:v2.9
    command:
      - --api.insecure=true
      - --providers.docker
      - --certificatesresolvers.default.acme.email=einnamehalt@f3r.eu
      - --certificatesresolvers.default.acme.email=einnamehalt@acme.json
      - --certificatesresolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - 
    privileged: true
    network_mode: "host"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./letsencrypt:/letsencrypt"