version: '3.8'

services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    restart: unless-stopped
    #ports:
    #  - '53:53/tcp'
    #  - '53:53/udp'
    #  - '67:67/udp'
    #  - '68:68/udp'
    #  - '80:80/tcp'
    #  - '443:443/tcp'
    #  - '443:443/udp'
    #  - '3000:3000/tcp'
    #  - '853:853/tcp'
    #  - '784:784/udp'
    #  - '853:853/udp'
    #  - '8853:8853/udp'
    #  - '5443:5443/tcp'
    #  - '5443:5443/udp'
    volumes:
      - 'home:/opt/adguardhome/work'
      - 'conf:/opt/adguardhome/conf'
    labels:  
      - "traefik.http.routers.adguardhome.rule=Host(`adguardhome.localhost`)"
      - "traefik.http.services.adguardhome.loadbalancer.server.port=80"
      - "traefik.http.routers.adguardhome.service=adguardhome"
      - "traefik.http.routers.bar.rule=Host(`bar.localhost`)"
      - "traefik.http.services.bar.loadbalancer.server.port=3000"
      - "traefik.http.routers.bar.service=bar"

volumes:
  home:
  conf: