name: "Deploy CloudFormation Stack"
on: 
  push:
    branches:
    - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Generate Ignition File
      uses: addnab/docker-run-action@v3
      with:
        image: quay.io/coreos/butane:release
        options: --security-opt label=disable -v ${{ github.workspace }}:/work --workdir /work  --rm --interactive
        run: |
          --strict -d ./ ./main.bu > ./ignition/main-x86_64.ign

    - name: ConvertBase64
      uses: frostebite/File-To-Base64@master
      id: base64Config
      with:
        filePath: ./ignition/main-x86_64.ign

    - name: Deploy CF Stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: test-endermite
        template: cf.yml
        parameter-overrides: "UserData=${{ steps.base64Config.outputs.base64 }}"
