name: "Test Branch Workflow"
on: 
  push:
    branches:
    - test

jobs:
  generate-ignition:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ "aarch64", "x86_64" ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Merge Butane Files for ARCH
      uses: mikefarah/yq@v4.30.8
      id: mergeButane
      with:
        cmd: yq '. *= load("main_${{ matrix.arch }}.bu")' main.bu > merged_main_${{ matrix.arch }}.bu

    - name: Generate Ignition File
      uses: addnab/docker-run-action@v3
      with:
        image: quay.io/coreos/butane:release
        options: --security-opt label=disable -v ${{ github.workspace }}:/work --workdir /work  --rm --interactive
        run: |
          /usr/local/bin/butane --strict -d ./ ./merged_main_${{ matrix.arch }}.bu > main-${{ matrix.arch }}.ign

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: main-${{ matrix.arch }}
        path: ./main-${{ matrix.arch }}.ign

  publish-ignition:
    runs-on: ubuntu-latest
    needs: [ generate-ignition ]
    steps:
        
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Download a Build Artifact
      id: dl
      uses: actions/download-artifact@v3
      with:
        path: ./ignition

    - name: Build app
      id: build
      run: |
        mv ./ignition/* ./ignition/

    - name: Add and Commit
      if: steps.dl.outcome == 'success'
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions

  deploy:
    runs-on: ubuntu-latest
    needs: [ publish-ignition ]
    steps:
        
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    
    - name: Generate Ignition File
      uses: addnab/docker-run-action@v3
      with:
        image: quay.io/coreos/butane:release
        options: --security-opt label=disable -v ${{ github.workspace }}:/work --workdir /work  --rm --interactive
        run: |
          /usr/local/bin/butane --strict ./test/remote.bu > ./test/remote.ign

    - name: ConvertBase64
      uses: frostebite/File-To-Base64@master
      id: base64Config
      with:
        filePath: ./test/remote.ign

    - name: Deploy CF Stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: test-endermite
        template: cf.yml
        parameter-overrides: "UserData=${{ steps.base64Config.outputs.base64 }}"
